# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  forest_env_secret: 93b619121344b1f81ae24495a1c4b4379f9ab32798515ef5e40b3fa01abfd0b9
  forest_auth_secret: X2NsHEzSZzqpcoUncQHs-w
  secret_key_base: 5fba44c63e6d4ffae2f97522ff2451719596fdac41ee7c46729b92f0dab5e5235ac8863f86bb9066383955c647f0d3426b2722030ef6ff6ae024f154fe54e2e3

test:
  secret_key_base: 69b9b967e6ff89f151df5d42ba051aaba396faf4d3e2df3dc47174de7deec494b145f16d731bba9c28f347b64f6264feb62a8188187eed2d7643a3c1dbb05dda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
